### ISSUE TITLE
Nice to have: Allow to connect one account to more than one provider.

### ISSUE THREAD

**Issue by jensens** [collective/pas.plugins.authomatic#11]
- Have one id connected to google and github and twitter.
- User logs in via Google.
- User adds github identity
- User has userdata from github.
- User add twitter identity
- User log out
- User logs in via twitter

Saved tokens can be used to query personal information from github or twitter.

**Comment by davisagli** [comment]
And similarly:
1. User creates "native" Plone login.
2. User adds identity & login from other providers to the same account 

David Glick
(mobile)

**Comment by jensens** [comment]
I started a branch, but at the moment massive WIP

**Comment by jensens** [comment]
half way done, but open issues moved to #13 #14 #15 in order to reduce scope
