### ISSUE TITLE
When you logout and then login again, a new user is created

### ISSUE THREAD

**Issue by sneridagh** [collective/pas.plugins.authomatic#21]
This is independent of the parametrization of the control panel's User ID option used. See screenshot:
<img width="858" alt="screen shot 2015-12-20 at 11 03 34" src="https://cloud.githubusercontent.com/assets/486927/11929766/0d9fd65a-a7de-11e5-8f1e-fc42bc016681.png">

**Comment by jensens** [comment]
indeed strange. i'll have a look
