### ISSUE TITLE
Stored state errors in fresh install

### ISSUE THREAD

**Issue by brett-kimball** [collective/pas.plugins.authomatic#29]
I have just installed pas.plone.authomatic in a fresh Plone5.0.6 buildout (no other packages installed).  Out of the box it is exhibiting errors retrieving the "stored state" during the oauth1 and oauth2 authorization flows.  With oauth2 I am seeing the "Unable to retrieve stored state!" error in Phase 2.  With oauth1 the error is "Unable to retrieve token secret from storage!".  These both appear to be cookie-related issues and are exhibited in Chrome/Firefox/IE browsers.

I can work around the oauth2 problem by setting "supports_csrf_protection = False" in authomatic.providers.oauth2.

Initially I was going to open this issue under peterhudec/authomatic, but then I realized that my earlier Plone5 buildout is not exhibiting the same problem and has the same package versions installed: authomatic = 0.1.0post1, pas.plugins.authomatic = 1.0a7.  That buildout has not been modified since April 26.  This leads me to believe that something has changed in Plone to render the authomatic plugin inoperative.

**Comment by brett-kimball** [comment]
Apparently the issue I was having was being caused by my Varnish Cache.  I have not yet determined exactly what was wrong and why it only impacted one Plone instance, but the problem outlined above has disappeared completely with the removal of Varnish.

**Comment by cdw9** [comment]
We ran into the same problem, and were able to exclude the authomatic url in Varnish to allow logins:

    if (req.url ~ "/authomatic-handler") {
       return(pipe);
    }
