### ISSUE TITLE
link is broken to JSON configuration documentation in help text

### ISSUE THREAD

**Issue by tkimnguyen** [collective/pas.plugins.authomatic#31]
http://peterhudec.github.io/authomatic/reference/providers.html is no longer valid. It redirects to http://peterhudec.com/ 

This is in the help text at https://github.com/collective/pas.plugins.authomatic/blob/6e6c9a9f2ac67365412b8e15b35e3d3151f0c07b/src/pas/plugins/authomatic/interfaces.py#L114 and in the README and .po and .pot files.

**Comment by jensens** [comment]
Project was moved to own organization, this need to be changed to http://authomatic.github.io/authomatic/reference/providers.html
