### ISSUE TITLE
Implement search by full name

### ISSUE THREAD

**Issue by jensens** [collective/pas.plugins.authomatic#32]
At the moment users are only searchable by their UID, which does not make much sense.

**Comment by cekk** [comment]
@jensens what's the status of this issue? I see that there is also a branch.
I started using this plugin and this behavior could be very useful.

**Comment by alecghica** [comment]
This would work https://github.com/eea/pas.plugins.authomatic/commit/4a2ca4adcd3f47e53ce1586bdad06c0e566c2eb9 but is not generic. I'll submit a PR when have the time to do so.
