### ISSUE TITLE
Page does not exist Control Settings

### ISSUE THREAD

**Issue by aogilvie** [collective/pas.plugins.authomatic#33]
- Using Docker plone image
- fresh plone install
- copy buildout.cfg, edit (add to eggs), cp into docker image, bin/buildout
- restart plone
- goto addons, install
- goto site preferences, see new icon under user/groups for authomatic settings
- click the new icon
- gotes to @@overview-controlpanel but page is not found.

Any ideas?

**Comment by jensens** [comment]
Looks like this is a problem with the special css to get the authomatic icon into the control panel. I guess it was a bad idea to do this. Needs revert to default icon.
