### ISSUE TITLE
Make it work in Plone 4. 

### ISSUE THREAD

**Issue by jensens** [collective/pas.plugins.authomatic#8]
at the moment broken in Plone 4.3.7 - primary because of registry specialities.

**Comment by gforcada** [comment]
I wouldn't consider that as a bug, but as a feature... ;-)

**Comment by jensens** [comment]
ok :)

**Comment by jensens** [comment]
Note: I will not implement this for 4.3 unless I need it in some project or someone pays me to implement it (both almost the same). If anybody want to implement - contributions welcome.

**Comment by keul** [comment]
Sadly we started using this for Plone 4 and now we see it's discontinued.
I'll try to reintroduce the Plone 4 support.

**Comment by jensens** [comment]
Since this is currently a side project of mine primary targeting new plone.org I just dont have time for this.
 
If you can keep an eye on it so Plone 4 tests are running again and the whole works on plone 4 I wont break it again! As always: Contributions are very welcome!

**Comment by keul** [comment]
Work in progress :smile:
